apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "flux"
spec:
  stages:
    - name: "test"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "test"
        - name: "promote"
    - name: "uat"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "test.delivery.finished"
        tasks: 
        - name: "test"
        - name: "promote"
    - name: "prod"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "uat.delivery.finished"
            selector:
              match:
              result: "pass"
        tasks: 
        - name: "test"